### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by storming0x** [Grandthrax/SingleSidedCurve#1]
Code Review on issues

**Comment by storming0x** [comment]
Suggestion: 

change modifier to use onlyAuthorized, guessing strategist needs to micro manage a few of these settings and may be to slow to only have governance. This is similar to other curve strats

```

    function updateMinTimePerInvest(uint256 _minTimePerInvest) public onlyGovernance {
        minTimePerInvest = _minTimePerInvest;
    }
    function updateMaxSingleInvest(uint256 _maxSingleInvest) public onlyGovernance {
        maxSingleInvest = _maxSingleInvest;
    }
    function updateSlippageProtection(uint256 _slippageProtection) public onlyGovernance {
        slippageProtection = _slippageProtection;
    }

```

**Comment by storming0x** [comment]
Question: 

I want orbxball to confirm the calculation in this method makes sense, i don't see it used in the same way in other Curve strats or maybe im reading it incorrectly

https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L92

**Comment by Grandthrax** [comment]
> Question:
> 
> I want orbxball to confirm the calculation in this method makes sense, i don't see it used in the same way in other Curve strats or maybe im reading it incorrectly

Normally people just use virtual price. I don't think that's safe enough so use the lower of virtual and real price.

**Comment by storming0x** [comment]
Suggestion:

Can save a bit of gas here copying the vault balance in memory
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L262

```
uint256 currentVaultBalance = yvhCRV.balanceOf(address(this));
if(amountFromVault > currentVaultBalance){
  amountFromVault = currentVaultBalance;
```
