### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by orbxball** [Grandthrax/SingleSidedCurve#2]

**Comment by orbxball** [comment]
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L101

does `cal_withdraw_one_coin` consider slippage internally?

**Comment by orbxball** [comment]
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L137-L139

so profit/loss is the current state of the strategy since beginning or profit/loss from last time call to this time call on `prepareReturn`?

**Comment by orbxball** [comment]
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L175

can make the `1` as `minSingleInvest`, so it can be modified later if needed. and `1` might be too small to cover `tend()` cost.

**Comment by orbxball** [comment]
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L192

is `cal_token_amount` a dry-run?

**Comment by orbxball** [comment]
https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L278

`>=` can save a little gas

**Comment by Grandthrax** [comment]
> https://github.com/Grandthrax/SingleSidedCurve/blob/0635ed99091bd961fb7ace0423d26c588df022e5/contracts/Strategy.sol#L278
> 
> `>=` can save a little gas

Yes

**Comment by Grandthrax** [comment]
> does `cal_withdraw_one_coin` consider slippage internally?

Yeah. it is the same as used internally in remove_liquidity_one_coin

**Comment by Grandthrax** [comment]
> is `cal_token_amount` a dry-run?

Yes. Problem with passing in slippage requirements to curve is that it reverts if we fail slippage. So need to do a dry run for alternative logic

**Comment by Grandthrax** [comment]
> can make the `1` as `minSingleInvest`, so it can be modified later if needed. and `1` might be too small to cover `tend()` cost.

sounds good

**Comment by Grandthrax** [comment]
> so profit/loss is the current state of the strategy since beginning or profit/loss from last time call to this time call on `prepareReturn`?

profit and loss is the difference since last time this was called.

**Comment by orbxball** [comment]
> > is `cal_token_amount` a dry-run?
> 
> Yes. Problem with passing in slippage requirements to curve is that it reverts if we fail slippage. So need to do a dry run for alternative logic

can use the revert to save some gas for keep3r credit.

**Comment by orbxball** [comment]
> > does `cal_withdraw_one_coin` consider slippage internally?
> 
> Yeah. it is the same as used internally in remove_liquidity_one_coin

afaik, it's not. but you always pick the lower value one. somewhat balance it.
